### ISSUE TITLE
Failures in flake8 tests

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros-tooling/aws-oncall#118]
## Overview

Several tests are failing due to an exception in flake8 tests.

Sample failure from system_metrics_collector:
```bash
13: Traceback (most recent call last):
  [15.061s] 13:   File "/usr/local/lib/python3.6/dist-packages/flake8/plugins/manager.py", line 157, in load_plugin
  [15.061s] 13:     self._load()
  [15.061s] 13:   File "/usr/local/lib/python3.6/dist-packages/flake8/plugins/manager.py", line 134, in _load
  [15.062s] 13:     self._plugin = self.entry_point.load()
  [15.062s] 13:   File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 97, in load
  [15.062s] 13:     return functools.reduce(getattr, attrs, module)
  [15.062s] 13: AttributeError: module 'pycodestyle' has no attribute 'break_around_binary_operator'
...
  [15.064s] 13: flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to module 'pycodestyle' has no attribute 'break_around_binary_operator'.

```

* [x] Add failure type label to this issue (build failure, test failure, build warning)
* [ ] Add environment labels to this issue (platform, arch - choose all that apply)
* [x] Please give a one sentence overview of the failure cause we're tracking
* [x] Please title this issue specifically but succinctly, e.g. :
    * "nightly linux armhf is failing rviz test"
    * "Windows Packaging build has linter errors"
    * "cmake warnings in all armhf nightly builds"

## Required Information

https://github.com/ros-tooling/system_metrics_collector/runs/686189835?check_suite_focus=true

**Comment by prajakta-gokhale** [comment]
The version of `ament_flake8` installed in these tests via apt does not support flake8 version 3.8. This [commit](https://github.com/ament/ament_lint/commit/3dab0c6f43a752b7b1bc20b26dec637579528cfd) that updates `ament_flake8` is not yet released.

**Comment by piraka9011** [comment]
`ament_lint` has been updated since `0.9.3` (https://github.com/ament/ament_lint/commit/8d85ab19e90341f4d3921e4bb4d6faecc5ed440c). Waiting for sync with apt.

Current issue is:

```
Traceback (most recent call last):
  File "/opt/ros/eloquent/bin/ament_flake8", line 11, in <module>
    load_entry_point('ament-flake8==0.8.1', 'console_scripts', 'ament_flake8')()
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ament_flake8/main.py", line 75, in main
    max_line_length=args.linelength)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ament_flake8/main.py", line 163, in generate_flake8_report
    style = get_flake8_style_guide(flake8_argv)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ament_flake8/main.py", line 131, in get_flake8_style_guide
    application.parse_preliminary_options_and_args([])
```

**Comment by thomas-moulard** [comment]
Closing as part of ops process changes. This issue is impacting our repos, but will be tracked in each project separately.
