### ISSUE TITLE
OSX Packaging build is failing

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros-tooling/aws-oncall#82]
## Overview

One of the builds we care about is not good!

* [x] Add failure type label to this issue (build failure, test failure, build warning)
* [x] Add environment labels to this issue (platform, arch - choose all that apply)
* [x] Please give a one sentence overview of the failure cause we're tracking
* [x] Please title this issue specifically but succinctly, e.g. :
    * "Windows Packaging build has linter errors"

## Required Information

* **Job Home**: https://ci.ros2.org/view/packaging/job/packaging_osx/
* **First Failing Build** https://ci.ros2.org/view/packaging/job/packaging_osx/1763/ 
* **Latest Failing Build** https://ci.ros2.org/view/packaging/job/packaging_osx/1764/ 
* **External tracking ticket**: None, see error details below.

Both builds mentioned above failed with an infrastructure error:

```bash
java.nio.channels.ClosedChannelException
23:16:38 	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
23:16:38 	at org.jenkinsci.remoting.protocol.impl.NIONetworkLayer.ready(NIONetworkLayer.java:179)
23:16:38 	at org.jenkinsci.remoting.protocol.IOHub$OnReady.run(IOHub.java:795)
23:16:38 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
23:16:38 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
23:16:38 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
23:16:38 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
23:16:38 	at java.lang.Thread.run(Thread.java:748)
23:16:38 Caused: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@1f4f0d1:JNLP4-connect connection from 70-35-50-58.static.wiline.com/70.35.50.58:59665": Remote call on JNLP4-connect connection from 70-35-50-58.static.wiline.com/70.35.50.58:59665 failed. The channel is closing down or has closed down
```

**Comment by prajakta-gokhale** [comment]
@mjcarroll is this being tracked anywhere?

**Comment by prajakta-gokhale** [comment]
Build is back to green.
